{"name": "test_valid_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: My Team menu item was not found after manager login\nStacktrace:\n\tGetHandleVerifier [0x00A91673+52979]\n\t(No symbol) [0x00A17961]\n\t(No symbol) [0x008FDD3D]\n\t(No symbol) [0x00935FBB]\n\t(No symbol) [0x009360FB]\n\t(No symbol) [0x0096CF92]\n\t(No symbol) [0x00954534]\n\t(No symbol) [0x0096B3FE]\n\t(No symbol) [0x00954286]\n\t(No symbol) [0x0092C063]\n\t(No symbol) [0x0092CECD]\n\tGetHandleVerifier [0x00DA8D83+3294723]\n\tGetHandleVerifier [0x00DE6CC2+3548482]\n\tGetHandleVerifier [0x00DE1C9C+3527964]\n\tGetHandleVerifier [0x00B2870E+671630]\n\t(No symbol) [0x00A21EB4]\n\t(No symbol) [0x00A1D808]\n\t(No symbol) [0x00A1D92D]\n\t(No symbol) [0x00A0F7E0]\n\tBaseThreadInitThunk [0x76F5FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AB7C6E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77AB7C3E+238]", "trace": "manager_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3d2332c23aa6257f6cc334d12c2233f0\")>\nconfig = {'baseUrl': 'http://172.22.1.141:8089/', 'browserType': 'chrome', 'employee': {'invalid_credentials': {'password': 'hg...d': 'hgukk', 'username': 'aaaaa'}, 'valid_manager_credentials': {'password': '45622', 'username': 'test-superviser2'}}}\nlogin_page = <src.pages.LoginPage.LoginPage object at 0x000001D5DBA503E0>\n\n    @pytest.mark.order(2)\n    def test_valid_login(manager_browser, config, login_page):\n        # Navigate to the login page using the 'baseUrl' from the base configuration\n        manager_browser.get(config['baseUrl'])\n    \n        # Perform a valid login using credentials from the manager configuration\n        login_page.login(\n            config['manager']['valid_manager_credentials']['username'],\n            config['manager']['valid_manager_credentials']['password']\n        )\n    \n        home_page = HomePage(manager_browser)\n    \n        # Alternatively, if you do not have WebDriverWait set up, a simple assertion could be:\n        # This assumes you have a method in your LoginPage to check for the \"My Team\" element\n>       assert home_page.is_my_team_visible(), \"My Team link should be visible for managers\"\n\ntest_manager\\test_manager_login.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nsrc\\pages\\HomePage.py:22: in is_my_team_visible\n    WebDriverWait(self.driver, 10).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"3d2332c23aa6257f6cc334d12c2233f0\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000001D5DBA44400>\nmessage = 'My Team menu item was not found after manager login'\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: My Team menu item was not found after manager login\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00A91673+52979]\nE       \t(No symbol) [0x00A17961]\nE       \t(No symbol) [0x008FDD3D]\nE       \t(No symbol) [0x00935FBB]\nE       \t(No symbol) [0x009360FB]\nE       \t(No symbol) [0x0096CF92]\nE       \t(No symbol) [0x00954534]\nE       \t(No symbol) [0x0096B3FE]\nE       \t(No symbol) [0x00954286]\nE       \t(No symbol) [0x0092C063]\nE       \t(No symbol) [0x0092CECD]\nE       \tGetHandleVerifier [0x00DA8D83+3294723]\nE       \tGetHandleVerifier [0x00DE6CC2+3548482]\nE       \tGetHandleVerifier [0x00DE1C9C+3527964]\nE       \tGetHandleVerifier [0x00B2870E+671630]\nE       \t(No symbol) [0x00A21EB4]\nE       \t(No symbol) [0x00A1D808]\nE       \t(No symbol) [0x00A1D92D]\nE       \t(No symbol) [0x00A0F7E0]\nE       \tBaseThreadInitThunk [0x76F5FCC9+25]\nE       \tRtlGetAppContainerNamedObjectPath [0x77AB7C6E+286]\nE       \tRtlGetAppContainerNamedObjectPath [0x77AB7C3E+238]\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "start": 1706983111299, "stop": 1706983122174, "uuid": "f3054cc2-2016-48bc-807b-77da8047720c", "historyId": "d3b39504f246c2a1778bf327525f9d79", "testCaseId": "d3b39504f246c2a1778bf327525f9d79", "fullName": "test_manager.test_manager_login#test_valid_login", "labels": [{"name": "tag", "value": "order(2)"}, {"name": "parentSuite", "value": "test_manager"}, {"name": "suite", "value": "test_manager_login"}, {"name": "host", "value": "Asal-AseelAssi"}, {"name": "thread", "value": "5296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_manager.test_manager_login"}]}